import { Body, Controller, Delete, Get, Param, ParseIntPipe, Patch, Post, Put, Query, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { CurrentUser } from '../common/decorators/current-user.decorator';
import { Permissions } from '../common/decorators/permissions.decorator';
import { PaginationDto } from '../common/dto/pagination.dto';
import { PermissionsGuard } from '../common/guards/permissions.guard';
import { CategoryDto, CustomerDto, ProductDto } from './catalog.dto';
import { CatalogAdminService } from './catalog.service';
@ApiTags('administración') @ApiBearerAuth() @UseGuards(JwtAuthGuard, PermissionsGuard) @Controller()
export class CatalogAdminController { constructor(private readonly service: CatalogAdminService) {} @Get('categorias') @Permissions('productos.ver') categories(@Query() q: PaginationDto) { return this.service.categoriesList(q); } @Post('categorias') @Permissions('productos.crear') createCategory(@Body() b: CategoryDto, @CurrentUser() u: { id: number }) { return this.service.createCategory(b, u.id); } @Get('categorias/:id') @Permissions('productos.ver') category(@Param('id', ParseIntPipe) id: number) { return this.service.category(id); } @Put('categorias/:id') @Permissions('productos.editar') updateCategory(@Param('id', ParseIntPipe) id: number, @Body() b: CategoryDto, @CurrentUser() u: { id: number }) { return this.service.updateCategory(id, b, u.id); } @Delete('categorias/:id') @Permissions('productos.eliminar') removeCategory(@Param('id', ParseIntPipe) id: number, @CurrentUser() u: { id: number }) { return this.service.deleteCategory(id, u.id); } @Get('productos') @Permissions('productos.ver') products(@Query() q: PaginationDto) { return this.service.productsList(q); } @Get('productos/:id') @Permissions('productos.ver') product(@Param('id', ParseIntPipe) id: number) { return this.service.product(id); } @Post('productos') @Permissions('productos.crear') createProduct(@Body() b: ProductDto, @CurrentUser() u: { id: number }) { return this.service.createProduct(b, u.id); } @Put('productos/:id') @Permissions('productos.editar') updateProduct(@Param('id', ParseIntPipe) id: number, @Body() b: ProductDto, @CurrentUser() u: { id: number }) { return this.service.updateProduct(id, b, u.id); } @Patch('productos/:id/estatus') @Permissions('productos.editar') statusProduct(@Param('id', ParseIntPipe) id: number, @Body('activo') activo: boolean, @CurrentUser() u: { id: number }) { return this.service.statusProduct(id, activo, u.id); } @Get('clientes') @Permissions('clientes.ver') customers(@Query() q: PaginationDto) { return this.service.customersList(q); } @Get('clientes/:id') @Permissions('clientes.ver') customer(@Param('id', ParseIntPipe) id: number) { return this.service.customer(id); } @Post('clientes') @Permissions('clientes.crear') createCustomer(@Body() b: CustomerDto, @CurrentUser() u: { id: number }) { return this.service.createCustomer(b, u.id); } @Put('clientes/:id') @Permissions('clientes.editar') updateCustomer(@Param('id', ParseIntPipe) id: number, @Body() b: CustomerDto, @CurrentUser() u: { id: number }) { return this.service.updateCustomer(id, b, u.id); } @Delete('clientes/:id') @Permissions('clientes.editar') deleteCustomer(@Param('id', ParseIntPipe) id: number, @CurrentUser() u: { id: number }) { return this.service.deleteCustomer(id, u.id); } }
