import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { ILike, ObjectLiteral, Repository } from 'typeorm';
import { AuditService } from '../audit/audit.service'; import { PaginationDto } from '../common/dto/pagination.dto'; import { Category, Customer, Product } from '../database/entities'; import { CategoryDto, CustomerDto, ProductDto } from './catalog.dto';
@Injectable() export class CatalogAdminService {
  constructor(@InjectRepository(Category) private categories:Repository<Category>,@InjectRepository(Product) private products:Repository<Product>,@InjectRepository(Customer) private customers:Repository<Customer>,private audit:AuditService) {}
  private async page<T extends ObjectLiteral>(repo:Repository<T>,q:PaginationDto,where:object,relations?:object){const sort=['id','nombre','createdAt','updatedAt'].includes(q.sort??'')?q.sort:'id';const[data,total]=await repo.findAndCount({where:where as never,relations,skip:(q.page-1)*q.limit,take:q.limit,order:{[sort]:q.order} as never});return{data,meta:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
  private async required<T extends ObjectLiteral>(repo:Repository<T>,id:number,businessId:number,relations?:object){const entity=await repo.findOne({where:{id,businessId} as never,relations});if(!entity)throw new NotFoundException({message:'Recurso no encontrado',errorCode:'NOT_FOUND'});return entity;}
  categoriesList(q:PaginationDto,businessId:number){return this.page(this.categories,q,q.search?{businessId,nombre:ILike(`%${q.search}%`)}:{businessId});}
  category(id:number,businessId:number){return this.required(this.categories,id,businessId);}
  async createCategory(d:CategoryDto,userId:number,businessId:number){if(await this.categories.exists({where:{businessId,nombre:d.nombre}}))throw new ConflictException({message:'La categoría ya existe',errorCode:'DUPLICATE_CATEGORY'});const entity=await this.categories.save(this.categories.create({...d,businessId}));await this.audit.log({userId,businessId,modulo:'CATEGORIAS',accion:'CATEGORIA_CREADA',entidad:'categorias',entidadId:String(entity.id),descripcion:`Categoría ${entity.nombre} creada`});return entity;}
  async updateCategory(id:number,d:Partial<CategoryDto>,userId:number,businessId:number){const entity=await this.required(this.categories,id,businessId);if(d.nombre&&d.nombre!==entity.nombre&&await this.categories.exists({where:{businessId,nombre:d.nombre}}))throw new ConflictException({message:'La categoría ya existe',errorCode:'DUPLICATE_CATEGORY'});Object.assign(entity,d);const saved=await this.categories.save(entity);await this.audit.log({userId,businessId,modulo:'CATEGORIAS',accion:'CATEGORIA_EDITADA',entidad:'categorias',entidadId:String(id),descripcion:`Categoría ${saved.nombre} editada`});return saved;}
  async deleteCategory(id:number,userId:number,businessId:number){if(await this.products.exists({where:{categoryId:id,businessId}}))throw new ConflictException({message:'Categoría en uso',errorCode:'CATEGORY_IN_USE'});await this.required(this.categories,id,businessId);await this.categories.softDelete(id);await this.audit.log({userId,businessId,modulo:'CATEGORIAS',accion:'CATEGORIA_ELIMINADA',entidad:'categorias',entidadId:String(id),descripcion:'Categoría eliminada'});return{message:'Categoría eliminada'};}
  productsList(q:PaginationDto,businessId:number){return this.page(this.products,q,q.search?{businessId,nombre:ILike(`%${q.search}%`)}:{businessId},{category:true});}
  product(id:number,businessId:number){return this.required(this.products,id,businessId,{category:true});}
  private async identifiers(d:Partial<ProductDto>,businessId:number,excludeId?:number){for(const[field,value,code]of[['sku',d.sku,'DUPLICATE_SKU'],['codigoBarras',d.codigoBarras,'DUPLICATE_BARCODE']]as const){if(!value)continue;const found=await this.products.findOne({where:{businessId,[field]:value}as never,withDeleted:true});if(found&&found.id!==excludeId)throw new ConflictException({message:field==='sku'?'SKU duplicado':'Código de barras duplicado',errorCode:code});}}
  async createProduct(d:ProductDto,userId:number,businessId:number){await this.required(this.categories,d.categoriaId,businessId);await this.identifiers(d,businessId);const entity=await this.products.save(this.products.create({...d,businessId,categoryId:d.categoriaId,precioCompra:String(d.precioCompra??0),precioVenta:String(d.precioVenta),stockActual:0,stockMinimo:d.stockMinimo??0}));await this.audit.log({userId,businessId,modulo:'PRODUCTOS',accion:'PRODUCTO_CREADO',entidad:'productos',entidadId:String(entity.id),descripcion:`Producto ${entity.nombre} creado`});return entity;}
  async updateProduct(id:number,d:Partial<ProductDto>,userId:number,businessId:number){const entity=await this.required(this.products,id,businessId);if(d.categoriaId!==undefined)await this.required(this.categories,d.categoriaId,businessId);await this.identifiers(d,businessId,id);Object.assign(entity,d,{categoryId:d.categoriaId??entity.categoryId,precioCompra:d.precioCompra===undefined?entity.precioCompra:String(d.precioCompra),precioVenta:d.precioVenta===undefined?entity.precioVenta:String(d.precioVenta)});const saved=await this.products.save(entity);await this.audit.log({userId,businessId,modulo:'PRODUCTOS',accion:'PRODUCTO_EDITADO',entidad:'productos',entidadId:String(id),descripcion:`Producto ${saved.nombre} editado`});return saved;}
  statusProduct(id:number,activo:boolean,userId:number,businessId:number){return this.updateProduct(id,{activo},userId,businessId);}
  customersList(q:PaginationDto,businessId:number){return this.page(this.customers,q,q.search?{businessId,nombre:ILike(`%${q.search}%`)}:{businessId});}
  customer(id:number,businessId:number){return this.required(this.customers,id,businessId);}
  async createCustomer(d:CustomerDto,userId:number,businessId:number){const entity=await this.customers.save(this.customers.create({...d,businessId}));await this.audit.log({userId,businessId,modulo:'CLIENTES',accion:'CLIENTE_CREADO',entidad:'clientes',entidadId:String(entity.id),descripcion:`Cliente ${entity.nombre} creado`});return entity;}
  async updateCustomer(id:number,d:Partial<CustomerDto>,userId:number,businessId:number){const entity=await this.required(this.customers,id,businessId);Object.assign(entity,d);const saved=await this.customers.save(entity);await this.audit.log({userId,businessId,modulo:'CLIENTES',accion:'CLIENTE_EDITADO',entidad:'clientes',entidadId:String(id),descripcion:`Cliente ${saved.nombre} editado`});return saved;}
  async deleteCustomer(id:number,userId:number,businessId:number){await this.required(this.customers,id,businessId);await this.customers.softDelete(id);await this.audit.log({userId,businessId,modulo:'CLIENTES',accion:'CLIENTE_ELIMINADO',entidad:'clientes',entidadId:String(id),descripcion:'Cliente eliminado'});return{message:'Cliente eliminado'};}
}
