import { Controller, Get, Query, UseGuards } from '@nestjs/common';
import { Type } from 'class-transformer';
import { IsInt, IsOptional, Max, Min } from 'class-validator';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ApiBearerAuth, ApiOperation, ApiQuery, ApiTags } from '@nestjs/swagger';
import { Product, Promotion, Reward, Sale } from '../database/entities';
import { RewardStatus, SaleStatus } from '../common/enums/domain.enums';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PermissionsGuard } from '../common/guards/permissions.guard';
import { Permissions } from '../common/decorators/permissions.decorator';

class RankingQuery { @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit = 10; }
@ApiTags('dashboard') @ApiBearerAuth() @UseGuards(JwtAuthGuard, PermissionsGuard) @Controller('dashboard')
export class DashboardController {
  constructor(@InjectRepository(Sale) private readonly sales: Repository<Sale>, @InjectRepository(Product) private readonly products: Repository<Product>, @InjectRepository(Promotion) private readonly promotions: Repository<Promotion>, @InjectRepository(Reward) private readonly rewards: Repository<Reward>) {}
  @Get('resumen') @Permissions('dashboard.ver') @ApiOperation({ summary: 'Indicadores económicos; excluye ventas canceladas' }) async summary() { const now = new Date(); const startDay = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const startWeek = new Date(startDay); startWeek.setDate(startDay.getDate() - startDay.getDay()); const startMonth = new Date(now.getFullYear(), now.getMonth(), 1); const totals = async (from: Date) => { const raw = await this.sales.createQueryBuilder('v').select('COUNT(*)', 'ventas').addSelect('COALESCE(SUM(v.total),0)', 'monto').where('v.estatus=:status', { status: SaleStatus.COMPLETADA }).andWhere('v.fecha_venta >= :from', { from }).getRawOne() as { ventas: string; monto: string }; return { ventas: Number(raw.ventas), monto: Number(raw.monto) }; }; const [hoy, semana, mes, bajo, agotados, activas, pending] = await Promise.all([totals(startDay), totals(startWeek), totals(startMonth), this.products.createQueryBuilder('p').where('p.activo=true AND p.stock_actual > 0 AND p.stock_actual <= p.stock_minimo').getMany(), this.products.find({ where: { activo: true, stockActual: 0 } }), this.promotions.count({ where: { activo: true } }), this.rewards.count({ where: { estatus: RewardStatus.DISPONIBLE } })]); return { hoy, semana, mes, productosStockBajo: bajo, productosAgotados: agotados, promocionesActivas: activas, recompensasPendientes: pending }; }
  @Get('productos-mas-vendidos') @Permissions('dashboard.ver') @ApiOperation({ summary: 'Ranking agregado de productos, sin ventas canceladas' }) @ApiQuery({ name: 'limit', required: false, type: Number }) async productsRanking(@Query() q: RankingQuery) { return this.sales.createQueryBuilder('v').innerJoin('v.details', 'd').innerJoin('d.product', 'p').select('p.id', 'productoId').addSelect('p.nombre', 'nombre').addSelect('SUM(d.cantidad)', 'cantidadVendida').addSelect('SUM(d.total)', 'importe').where('v.estatus = :status', { status: SaleStatus.COMPLETADA }).groupBy('p.id').addGroupBy('p.nombre').orderBy('cantidadVendida', 'DESC').addOrderBy('importe', 'DESC').limit(q.limit).getRawMany(); }
  @Get('categorias-mas-vendidas') @Permissions('dashboard.ver') @ApiOperation({ summary: 'Ranking agregado de categorías, sin ventas canceladas' }) @ApiQuery({ name: 'limit', required: false, type: Number }) async categoriesRanking(@Query() q: RankingQuery) { return this.sales.createQueryBuilder('v').innerJoin('v.details', 'd').innerJoin('d.product', 'p').innerJoin('p.category', 'c').select('c.id', 'categoriaId').addSelect('c.nombre', 'nombre').addSelect('SUM(d.cantidad)', 'cantidadVendida').addSelect('SUM(d.total)', 'importe').where('v.estatus = :status', { status: SaleStatus.COMPLETADA }).groupBy('c.id').addGroupBy('c.nombre').orderBy('cantidadVendida', 'DESC').addOrderBy('importe', 'DESC').limit(q.limit).getRawMany(); }
}
