import { MigrationInterface, QueryRunner } from 'typeorm';

export class MultibusinessFoundation1730000000000 implements MigrationInterface {
  name = 'MultibusinessFoundation1730000000000';
  async up(q: QueryRunner) {
    await q.query("CREATE TABLE negocios (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(150) NOT NULL, slug VARCHAR(160) NOT NULL UNIQUE, logo_url VARCHAR(500) NULL, telefono VARCHAR(30) NULL, whatsapp VARCHAR(30) NULL, moneda VARCHAR(8) NOT NULL DEFAULT 'MXN', zona_horaria VARCHAR(80) NOT NULL DEFAULT 'America/Hermosillo', estatus ENUM('ACTIVO','SUSPENDIDO','DESACTIVADO') NOT NULL DEFAULT 'ACTIVO', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    await q.query("INSERT INTO negocios (nombre,slug,moneda,zona_horaria) SELECT COALESCE(NULLIF(nombre_negocio,''),'ChuyDesk'), 'negocio-original', moneda, zona_horaria FROM configuracion ORDER BY id ASC LIMIT 1");
    await q.query("INSERT INTO negocios (nombre,slug) SELECT 'ChuyDesk','negocio-original' WHERE NOT EXISTS (SELECT 1 FROM negocios)");
    await q.query("ALTER TABLE usuarios ADD COLUMN es_administrador_plataforma TINYINT NOT NULL DEFAULT 0 AFTER rol_id");
    await q.query("UPDATE usuarios u INNER JOIN roles r ON r.id=u.rol_id SET u.es_administrador_plataforma=1 WHERE r.nombre='ADMIN'");
    await q.query("CREATE TABLE negocio_usuarios (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, negocio_id BIGINT UNSIGNED NOT NULL, usuario_id BIGINT UNSIGNED NOT NULL, rol_id BIGINT UNSIGNED NOT NULL, estatus ENUM('ACTIVA','INACTIVA') NOT NULL DEFAULT 'ACTIVA', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY UQ_negocio_usuarios_negocio_usuario (negocio_id,usuario_id), INDEX IDX_negocio_usuarios_estatus (estatus), FOREIGN KEY (negocio_id) REFERENCES negocios(id), FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY (rol_id) REFERENCES roles(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    await q.query('INSERT INTO negocio_usuarios (negocio_id,usuario_id,rol_id) SELECT (SELECT id FROM negocios ORDER BY id ASC LIMIT 1), id, rol_id FROM usuarios WHERE deleted_at IS NULL');
    for (const table of ['categorias','productos','clientes','configuracion','promociones','ventas','movimientos_inventario','cliente_promociones','recompensas','progreso_lealtad_ventas','bitacora']) await q.query(`ALTER TABLE ${table} ADD COLUMN negocio_id BIGINT UNSIGNED NULL`);
    const business = '(SELECT id FROM negocios ORDER BY id ASC LIMIT 1)';
    for (const table of ['categorias','productos','clientes','configuracion','promociones','ventas','movimientos_inventario','cliente_promociones','recompensas','progreso_lealtad_ventas','bitacora']) await q.query(`UPDATE ${table} SET negocio_id=${business}`);
    for (const table of ['categorias','productos','clientes','configuracion','promociones','ventas','movimientos_inventario','cliente_promociones','recompensas','progreso_lealtad_ventas']) { await q.query(`ALTER TABLE ${table} MODIFY COLUMN negocio_id BIGINT UNSIGNED NOT NULL, ADD INDEX IDX_${table}_negocio (negocio_id), ADD CONSTRAINT FK_${table}_negocio FOREIGN KEY (negocio_id) REFERENCES negocios(id)`); }
    await q.query('ALTER TABLE bitacora ADD INDEX IDX_bitacora_negocio (negocio_id), ADD CONSTRAINT FK_bitacora_negocio FOREIGN KEY (negocio_id) REFERENCES negocios(id)');
    await q.query('ALTER TABLE categorias DROP INDEX nombre, ADD UNIQUE KEY UQ_categorias_negocio_nombre (negocio_id,nombre)');
    await q.query('ALTER TABLE productos DROP INDEX sku, DROP INDEX UQ_productos_codigo_barras, ADD UNIQUE KEY UQ_productos_negocio_sku (negocio_id,sku), ADD UNIQUE KEY UQ_productos_negocio_codigo_barras (negocio_id,codigo_barras)');
    await q.query('ALTER TABLE ventas DROP INDEX folio, ADD UNIQUE KEY UQ_ventas_negocio_folio (negocio_id,folio)');
    await q.query('ALTER TABLE configuracion ADD UNIQUE KEY UQ_configuracion_negocio (negocio_id)');
  }
  async down(q: QueryRunner) { await q.query('ALTER TABLE configuracion DROP INDEX UQ_configuracion_negocio'); await q.query('ALTER TABLE ventas DROP INDEX UQ_ventas_negocio_folio, ADD UNIQUE KEY folio (folio)'); await q.query('ALTER TABLE productos DROP INDEX UQ_productos_negocio_sku, DROP INDEX UQ_productos_negocio_codigo_barras, ADD UNIQUE KEY sku (sku), ADD UNIQUE KEY UQ_productos_codigo_barras (codigo_barras)'); await q.query('ALTER TABLE categorias DROP INDEX UQ_categorias_negocio_nombre, ADD UNIQUE KEY nombre (nombre)'); for (const table of ['bitacora','progreso_lealtad_ventas','recompensas','cliente_promociones','movimientos_inventario','ventas','promociones','configuracion','clientes','productos','categorias']) { await q.query(`ALTER TABLE ${table} DROP FOREIGN KEY FK_${table}_negocio, DROP INDEX IDX_${table}_negocio, DROP COLUMN negocio_id`); } await q.query('DROP TABLE negocio_usuarios'); await q.query('ALTER TABLE usuarios DROP COLUMN es_administrador_plataforma'); await q.query('DROP TABLE negocios'); }
}
