import { MigrationInterface, QueryRunner } from 'typeorm';
export class CustomerCreditAccountsAndProductImages1740000000000 implements MigrationInterface {
  name='CustomerCreditAccountsAndProductImages1740000000000';
  async up(q:QueryRunner){
    await q.query("ALTER TABLE clientes ADD COLUMN saldo_actual DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER activo");
    await q.query("ALTER TABLE ventas ADD COLUMN tipo_pago ENUM('CONTADO','CREDITO','MIXTO') NOT NULL DEFAULT 'CONTADO' AFTER total, ADD COLUMN pago_inicial DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER tipo_pago, ADD COLUMN saldo_pendiente DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER pago_inicial");
    await q.query("CREATE TABLE abonos_cliente (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, negocio_id BIGINT UNSIGNED NOT NULL, cliente_id BIGINT UNSIGNED NOT NULL, usuario_id BIGINT UNSIGNED NOT NULL, monto DECIMAL(12,2) NOT NULL, metodo ENUM('EFECTIVO','TRANSFERENCIA','TARJETA','OTRO') NOT NULL, cancelado TINYINT NOT NULL DEFAULT 0, motivo_cancelacion TEXT NULL, fecha_cancelacion DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX IDX_abonos_cliente_negocio (negocio_id), INDEX IDX_abonos_cliente_cliente (cliente_id), FOREIGN KEY (negocio_id) REFERENCES negocios(id), FOREIGN KEY (cliente_id) REFERENCES clientes(id), FOREIGN KEY (usuario_id) REFERENCES usuarios(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    await q.query("CREATE TABLE cliente_cuenta_movimientos (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, negocio_id BIGINT UNSIGNED NOT NULL, cliente_id BIGINT UNSIGNED NOT NULL, usuario_id BIGINT UNSIGNED NULL, tipo ENUM('VENTA_CREDITO','ABONO','AJUSTE_CARGO','AJUSTE_ABONO','CANCELACION_VENTA','CANCELACION_ABONO') NOT NULL, saldo_anterior DECIMAL(12,2) NOT NULL, cargo DECIMAL(12,2) NOT NULL DEFAULT 0, abono DECIMAL(12,2) NOT NULL DEFAULT 0, saldo_nuevo DECIMAL(12,2) NOT NULL, referencia VARCHAR(100) NULL, observaciones TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX IDX_cliente_cuenta_movimientos_negocio (negocio_id), INDEX IDX_cliente_cuenta_movimientos_cliente (cliente_id), FOREIGN KEY (negocio_id) REFERENCES negocios(id), FOREIGN KEY (cliente_id) REFERENCES clientes(id), FOREIGN KEY (usuario_id) REFERENCES usuarios(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  }
  async down(q:QueryRunner){await q.query('DROP TABLE cliente_cuenta_movimientos');await q.query('DROP TABLE abonos_cliente');await q.query('ALTER TABLE ventas DROP COLUMN saldo_pendiente, DROP COLUMN pago_inicial, DROP COLUMN tipo_pago');await q.query('ALTER TABLE clientes DROP COLUMN saldo_actual');}
}
