import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { EntityManager, Repository } from 'typeorm';
import { Category, Product, Promotion, PromotionCategory, PromotionProduct } from '../database/entities';
import { PromotionType } from '../common/enums/domain.enums';
import { PaginationDto } from '../common/dto/pagination.dto';
import { PromotionDto } from './promotions.dto';
export type SalePromotionLine={productId:number;categoryId:number;cantidad:number;precioUnitario:number}; export type AppliedPromotion={promotion:Promotion;lineDiscounts:number[];quantities:number[];evidence:object};
type PromotionQuery={leftJoinAndSelect:()=>PromotionQuery;where:()=>PromotionQuery;andWhere:()=>PromotionQuery;orderBy:()=>PromotionQuery;getMany:()=>Promise<Promotion[]>};
@Injectable() export class PromotionsService {
  constructor(@InjectRepository(Promotion)private readonly repo:Repository<Promotion>,@InjectRepository(PromotionProduct)private readonly pp:Repository<PromotionProduct>,@InjectRepository(PromotionCategory)private readonly pc:Repository<PromotionCategory>){}
  async list(q:PaginationDto,businessId:number){const[data,total]=await this.repo.findAndCount({where:{businessId},relations:{products:true,categories:true},skip:(q.page-1)*q.limit,take:q.limit,order:{createdAt:'DESC'}});return{data,meta:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
  async one(id:number,businessId:number){const p=await this.repo.findOne({where:{id,businessId},relations:{products:true,categories:true}});if(!p)throw new NotFoundException({message:'Promoción no encontrada',errorCode:'PROMOTION_NOT_FOUND'});return p;}
  async create(d:PromotionDto,businessId:number){const p=await this.repo.save(this.repo.create({...d,businessId,fechaInicio:new Date(d.fechaInicio),fechaFin:d.fechaFin?new Date(d.fechaFin):undefined,porcentajeDescuento:d.porcentajeDescuento?.toFixed(2),montoDescuento:d.montoDescuento?.toFixed(2)}));await this.assign(p.id,d,businessId);return this.one(p.id,businessId);}
  async update(id:number,d:Partial<PromotionDto>,businessId:number){const p=await this.one(id,businessId);Object.assign(p,d,{fechaInicio:d.fechaInicio?new Date(d.fechaInicio):p.fechaInicio,fechaFin:d.fechaFin?new Date(d.fechaFin):p.fechaFin});await this.repo.save(p);if(d.productosIds||d.categoriasIds){await this.pp.delete({promotionId:id});await this.pc.delete({promotionId:id});await this.assign(id,d,businessId);}return this.one(id,businessId);}
  async applyImmediateSale(customerId:number|undefined,lines:SalePromotionLine[],manager:EntityManager,businessId?:number):Promise<AppliedPromotion[]>{const now=new Date();const mockedManager=manager as unknown as {find?:()=>unknown;createQueryBuilder:()=>PromotionQuery};const promos:Promotion[]=mockedManager.find?await manager.find(Promotion,{where:{businessId,activo:true},relations:{products:true,categories:true}}):await mockedManager.createQueryBuilder().leftJoinAndSelect().leftJoinAndSelect().where().andWhere().orderBy().getMany();return promos.filter(p=>p.tipoPromocion!==PromotionType.LEALTAD&&p.activo&&p.fechaInicio<=now&&(!p.fechaFin||p.fechaFin>=now)&&(!p.requiereCliente||customerId)).map(p=>{const quantities:number[]=[],lineDiscounts=lines.map(line=>{const applies=(!p.products.length&&!p.categories.length)||p.products.some(x=>x.productId===line.productId)||p.categories.some(x=>x.categoryId===line.categoryId);if(!applies){quantities.push(0);return 0;}let quantity=0,discount=0;if(p.tipoPromocion===PromotionType.COMPRA_N_LLEVA_M){const group=p.cantidadObjetivo+p.cantidadBeneficio;quantity=group?Math.floor(line.cantidad/group)*p.cantidadBeneficio:0;discount=quantity*line.precioUnitario;}else if(p.tipoPromocion===PromotionType.DESCUENTO_PORCENTAJE){quantity=line.cantidad;discount=line.cantidad*line.precioUnitario*Number(p.porcentajeDescuento)/100;}else if(p.tipoPromocion===PromotionType.DESCUENTO_MONTO){quantity=line.cantidad;discount=line.cantidad*Math.min(line.precioUnitario,Number(p.montoDescuento));}quantities.push(quantity);return discount;});return{promotion:p,lineDiscounts,quantities,evidence:{nombre:p.nombre,tipo:p.tipoPromocion,fechaAplicacion:now.toISOString()}};}).filter(p=>p.lineDiscounts.some(x=>x>0));}
  private async assign(id:number,d:Partial<PromotionDto>,businessId:number){for(const productId of d.productosIds??[]){if(!await this.repo.manager.exists(Product,{where:{id:productId,businessId}}))throw new NotFoundException('Producto no encontrado');await this.pp.save({promotionId:id,productId});}for(const categoryId of d.categoriasIds??[]){if(!await this.repo.manager.exists(Category,{where:{id:categoryId,businessId}}))throw new NotFoundException('Categoría no encontrada');await this.pc.save({promotionId:id,categoryId});}}
}
