import { Column, Entity, JoinColumn, ManyToOne, OneToMany, Unique } from 'typeorm';
import { PromotionType, RewardStatus } from '../../common/enums/domain.enums';
import { Category, Customer, Product } from './catalog.entities';
import { SoftDeleteEntity, TimestampedEntity } from './base.entity';
import { Sale } from './sales.entities';
import { User } from './security.entities';
import { Business } from './business.entities';

@Entity('promociones') export class Promotion extends SoftDeleteEntity { @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @Column({length:150}) nombre:string; @Column({type:'text',nullable:true}) descripcion?:string; @Column({name:'tipo_promocion',type:'enum',enum:PromotionType}) tipoPromocion:PromotionType; @Column({name:'cantidad_objetivo',type:'int',unsigned:true,default:1}) cantidadObjetivo:number; @Column({name:'cantidad_beneficio',type:'int',unsigned:true,default:0}) cantidadBeneficio:number; @Column({name:'porcentaje_descuento',type:'decimal',precision:5,scale:2,nullable:true}) porcentajeDescuento?:string; @Column({name:'monto_descuento',type:'decimal',precision:12,scale:2,nullable:true}) montoDescuento?:string; @Column({name:'fecha_inicio',type:'datetime'}) fechaInicio:Date; @Column({name:'fecha_fin',type:'datetime',nullable:true}) fechaFin?:Date; @Column({name:'requiere_cliente',default:false}) requiereCliente:boolean; @Column({default:true}) activo:boolean; @OneToMany(()=>PromotionProduct,x=>x.promotion,{cascade:true}) products:PromotionProduct[]; @OneToMany(()=>PromotionCategory,x=>x.promotion,{cascade:true}) categories:PromotionCategory[]; }
@Entity('promocion_productos') @Unique(['promotionId','productId']) export class PromotionProduct extends TimestampedEntity { @ManyToOne(()=>Promotion,p=>p.products,{onDelete:'CASCADE'}) @JoinColumn({name:'promocion_id'}) promotion:Promotion; @Column({name:'promocion_id',type:'bigint',unsigned:true}) promotionId:number; @ManyToOne(()=>Product) @JoinColumn({name:'producto_id'}) product:Product; @Column({name:'producto_id',type:'bigint',unsigned:true}) productId:number; }
@Entity('promocion_categorias') @Unique(['promotionId','categoryId']) export class PromotionCategory extends TimestampedEntity { @ManyToOne(()=>Promotion,p=>p.categories,{onDelete:'CASCADE'}) @JoinColumn({name:'promocion_id'}) promotion:Promotion; @Column({name:'promocion_id',type:'bigint',unsigned:true}) promotionId:number; @ManyToOne(()=>Category) @JoinColumn({name:'categoria_id'}) category:Category; @Column({name:'categoria_id',type:'bigint',unsigned:true}) categoryId:number; }
@Entity('cliente_promociones') @Unique(['customerId','promotionId']) export class CustomerPromotion extends TimestampedEntity { @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @ManyToOne(()=>Customer) @JoinColumn({name:'cliente_id'}) customer:Customer; @Column({name:'cliente_id',type:'bigint',unsigned:true}) customerId:number; @ManyToOne(()=>Promotion) @JoinColumn({name:'promocion_id'}) promotion:Promotion; @Column({name:'promocion_id',type:'bigint',unsigned:true}) promotionId:number; @Column({name:'progreso_actual',type:'int',unsigned:true,default:0}) progresoActual:number; @Column({name:'recompensas_generadas',type:'int',unsigned:true,default:0}) recompensasGeneradas:number; @Column({name:'recompensas_disponibles',type:'int',unsigned:true,default:0}) recompensasDisponibles:number; @Column({name:'recompensas_utilizadas',type:'int',unsigned:true,default:0}) recompensasUtilizadas:number; @Column({name:'ultima_actualizacion',type:'datetime',nullable:true}) ultimaActualizacion?:Date; }
@Entity('recompensas') export class Reward extends TimestampedEntity { @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @ManyToOne(()=>Customer) @JoinColumn({name:'cliente_id'}) customer:Customer; @Column({name:'cliente_id',type:'bigint',unsigned:true}) customerId:number; @ManyToOne(()=>Promotion) @JoinColumn({name:'promocion_id'}) promotion:Promotion; @Column({name:'promocion_id',type:'bigint',unsigned:true}) promotionId:number; @ManyToOne(()=>Product,{nullable:true}) @JoinColumn({name:'producto_id'}) product?:Product; @Column({name:'producto_id',type:'bigint',unsigned:true,nullable:true}) productId?:number; @Column({type:'text'}) descripcion:string; @Column({type:'json',nullable:true}) evidencia?:object; @Column({type:'enum',enum:RewardStatus,default:RewardStatus.DISPONIBLE}) estatus:RewardStatus; @Column({name:'generada_en',type:'datetime'}) generadaEn:Date; @Column({name:'expira_en',type:'datetime',nullable:true}) expiraEn?:Date; @Column({name:'canjeada_en',type:'datetime',nullable:true}) canjeadaEn?:Date; @ManyToOne(()=>User,{nullable:true}) @JoinColumn({name:'usuario_canje_id'}) usuarioCanje?:User; @Column({name:'usuario_canje_id',type:'bigint',unsigned:true,nullable:true}) usuarioCanjeId?:number; @ManyToOne(()=>Sale) @JoinColumn({name:'venta_generadora_id'}) saleGeneradora:Sale; @Column({name:'venta_generadora_id',type:'bigint',unsigned:true}) saleGeneradoraId:number; @ManyToOne(()=>Sale,{nullable:true}) @JoinColumn({name:'venta_canje_id'}) saleCanje?:Sale; @Column({name:'venta_canje_id',type:'bigint',unsigned:true,nullable:true}) saleCanjeId?:number; }
@Entity('progreso_lealtad_ventas') @Unique(['saleId','promotionId']) export class LoyaltyProgressEvent extends TimestampedEntity { @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @ManyToOne(()=>Sale,{onDelete:'RESTRICT'}) @JoinColumn({name:'venta_id'}) sale:Sale; @Column({name:'venta_id',type:'bigint',unsigned:true}) saleId:number; @ManyToOne(()=>Customer) @JoinColumn({name:'cliente_id'}) customer:Customer; @Column({name:'cliente_id',type:'bigint',unsigned:true}) customerId:number; @ManyToOne(()=>Promotion) @JoinColumn({name:'promocion_id'}) promotion:Promotion; @Column({name:'promocion_id',type:'bigint',unsigned:true}) promotionId:number; @Column({name:'cantidad_elegible',type:'int',unsigned:true}) cantidadElegible:number; }
