import { Column, Entity, Index, JoinColumn, ManyToOne, OneToMany } from 'typeorm';
import { CustomerAccountMovementType, InventoryMovementType, PaymentMethod, PromotionType, SalePaymentType, SaleStatus } from '../../common/enums/domain.enums';
import { Product, Customer } from './catalog.entities';
import { Promotion } from './promotion.entities';
import { TimestampedEntity } from './base.entity';
import { User } from './security.entities';
import { Business } from './business.entities';

@Entity('ventas') export class Sale extends TimestampedEntity { @Index() @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @Column({length:40}) folio:string; @ManyToOne(()=>Customer,{nullable:true}) @JoinColumn({name:'cliente_id'}) customer?:Customer; @Column({name:'cliente_id',type:'bigint',unsigned:true,nullable:true}) customerId?:number; @ManyToOne(()=>User) @JoinColumn({name:'usuario_id'}) user:User; @Column({name:'usuario_id',type:'bigint',unsigned:true}) userId:number; @Column({type:'decimal',precision:12,scale:2}) subtotal:string; @Column({type:'decimal',precision:12,scale:2,default:0}) descuento:string; @Column({type:'decimal',precision:12,scale:2}) total:string; @Column({name:'tipo_pago',type:'enum',enum:SalePaymentType,default:SalePaymentType.CONTADO}) tipoPago:SalePaymentType; @Column({name:'pago_inicial',type:'decimal',precision:12,scale:2,default:0}) pagoInicial:string; @Column({name:'saldo_pendiente',type:'decimal',precision:12,scale:2,default:0}) saldoPendiente:string; @Column({type:'enum',enum:SaleStatus,default:SaleStatus.COMPLETADA}) estatus:SaleStatus; @Column({type:'text',nullable:true}) observaciones?:string; @Index() @Column({name:'fecha_venta',type:'datetime'}) fechaVenta:Date; @OneToMany(()=>SaleDetail,d=>d.sale,{cascade:true}) details:SaleDetail[]; }
@Entity('venta_detalle') export class SaleDetail extends TimestampedEntity { @ManyToOne(()=>Sale,s=>s.details,{onDelete:'RESTRICT'}) @JoinColumn({name:'venta_id'}) sale:Sale; @Column({name:'venta_id',type:'bigint',unsigned:true}) saleId:number; @ManyToOne(()=>Product) @JoinColumn({name:'producto_id'}) product:Product; @Column({name:'producto_id',type:'bigint',unsigned:true}) productId:number; @Column({type:'int',unsigned:true}) cantidad:number; @Column({name:'precio_unitario',type:'decimal',precision:12,scale:2}) precioUnitario:string; @Column({type:'decimal',precision:12,scale:2,default:0}) descuento:string; @Column({type:'decimal',precision:12,scale:2}) subtotal:string; @Column({type:'decimal',precision:12,scale:2}) total:string; }
@Entity('venta_promociones') export class SalePromotionApplication extends TimestampedEntity { @ManyToOne(()=>Sale,{onDelete:'RESTRICT'}) @JoinColumn({name:'venta_id'}) sale:Sale; @Column({name:'venta_id',type:'bigint',unsigned:true}) saleId:number; @ManyToOne(()=>SaleDetail,{nullable:true,onDelete:'RESTRICT'}) @JoinColumn({name:'venta_detalle_id'}) saleDetail?:SaleDetail; @Column({name:'venta_detalle_id',type:'bigint',unsigned:true,nullable:true}) saleDetailId?:number; @ManyToOne(()=>Promotion) @JoinColumn({name:'promocion_id'}) promotion:Promotion; @Column({name:'promocion_id',type:'bigint',unsigned:true}) promotionId:number; @Column({name:'tipo_promocion',type:'enum',enum:PromotionType}) tipoPromocion:PromotionType; @Column({name:'cantidad_beneficiada',type:'int',unsigned:true,default:0}) cantidadBeneficiada:number; @Column({type:'decimal',precision:12,scale:2}) descuento:string; @Column({type:'json'}) evidencia:object; }
@Entity('movimientos_inventario') export class InventoryMovement extends TimestampedEntity { @Index() @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @ManyToOne(()=>Product,p=>p.movements) @JoinColumn({name:'producto_id'}) product:Product; @Column({name:'producto_id',type:'bigint',unsigned:true}) productId:number; @ManyToOne(()=>User,{nullable:true}) @JoinColumn({name:'usuario_id'}) user?:User; @Column({name:'usuario_id',type:'bigint',unsigned:true,nullable:true}) userId?:number; @Column({name:'tipo_movimiento',type:'enum',enum:InventoryMovementType}) tipoMovimiento:InventoryMovementType; @Column({type:'int'}) cantidad:number; @Column({name:'stock_anterior',type:'int',unsigned:true}) stockAnterior:number; @Column({name:'stock_nuevo',type:'int',unsigned:true}) stockNuevo:number; @Column({name:'referencia_tipo',nullable:true,length:50}) referenciaTipo?:string; @Column({name:'referencia_id',nullable:true,length:60}) referenciaId?:string; @Column({nullable:true,length:255}) motivo?:string; @Column({type:'text',nullable:true}) observaciones?:string; }
@Entity('abonos_cliente') export class CustomerPayment extends TimestampedEntity { @Index() @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @ManyToOne(()=>Customer,{onDelete:'RESTRICT'}) @JoinColumn({name:'cliente_id'}) customer:Customer; @Column({name:'cliente_id',type:'bigint',unsigned:true}) customerId:number; @ManyToOne(()=>User) @JoinColumn({name:'usuario_id'}) user:User; @Column({name:'usuario_id',type:'bigint',unsigned:true}) userId:number; @Column({type:'decimal',precision:12,scale:2}) monto:string; @Column({type:'enum',enum:PaymentMethod}) metodo:PaymentMethod; @Column({default:false}) cancelado:boolean; @Column({name:'motivo_cancelacion',type:'text',nullable:true}) motivoCancelacion?:string; @Column({name:'fecha_cancelacion',type:'datetime',nullable:true}) fechaCancelacion?:Date; }
@Entity('cliente_cuenta_movimientos') export class CustomerAccountMovement extends TimestampedEntity { @Index() @Column({name:'negocio_id',type:'bigint',unsigned:true}) businessId:number; @ManyToOne(()=>Business,{onDelete:'RESTRICT'}) @JoinColumn({name:'negocio_id'}) business:Business; @Index() @Column({name:'cliente_id',type:'bigint',unsigned:true}) customerId:number; @ManyToOne(()=>Customer,{onDelete:'RESTRICT'}) @JoinColumn({name:'cliente_id'}) customer:Customer; @ManyToOne(()=>User,{nullable:true}) @JoinColumn({name:'usuario_id'}) user?:User; @Column({name:'usuario_id',type:'bigint',unsigned:true,nullable:true}) userId?:number; @Column({type:'enum',enum:CustomerAccountMovementType}) tipo:CustomerAccountMovementType; @Column({name:'saldo_anterior',type:'decimal',precision:12,scale:2}) saldoAnterior:string; @Column({type:'decimal',precision:12,scale:2,default:0}) cargo:string; @Column({type:'decimal',precision:12,scale:2,default:0}) abono:string; @Column({name:'saldo_nuevo',type:'decimal',precision:12,scale:2}) saldoNuevo:string; @Column({nullable:true,length:100}) referencia?:string; @Column({type:'text',nullable:true}) observaciones?:string; }
