import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityManager, Repository } from 'typeorm';
import { AuditService } from '../audit/audit.service';
import { PaginationDto } from '../common/dto/pagination.dto';
import { CustomerAccountMovementType } from '../common/enums/domain.enums';
import { Customer, CustomerAccountMovement, CustomerPayment } from '../database/entities';
import { CancelCustomerPaymentDto, CreateCustomerPaymentDto } from './accounts.dto';

@Injectable()
export class AccountsService {
  constructor(private readonly ds:DataSource,@InjectRepository(Customer) private readonly customers:Repository<Customer>,@InjectRepository(CustomerPayment) private readonly payments:Repository<CustomerPayment>,@InjectRepository(CustomerAccountMovement) private readonly movements:Repository<CustomerAccountMovement>,private readonly audit:AuditService) {}
  private money(value:number){return value.toFixed(2);}
  private async customer(id:number,businessId:number,manager:EntityManager=this.ds.manager,lock=false){const customer=await manager.findOne(Customer,{where:{id,businessId,activo:true},...(lock?{lock:{mode:'pessimistic_write' as const}}:{})});if(!customer)throw new NotFoundException({message:'Cliente no encontrado',errorCode:'CUSTOMER_NOT_FOUND'});return customer;}
  async addMovement(input:{customerId:number;businessId:number;userId?:number;type:CustomerAccountMovementType;charge?:number;payment?:number;reference?:string;observations?:string},manager:EntityManager=this.ds.manager){const customer=await this.customer(input.customerId,input.businessId,manager,true);const previous=Number(customer.saldoActual),charge=input.charge??0,payment=input.payment??0,next=Number((previous+charge-payment).toFixed(2));if(next<-0.005)throw new BadRequestException({message:'El abono excede el saldo pendiente',errorCode:'PAYMENT_EXCEEDS_BALANCE'});customer.saldoActual=this.money(Math.max(0,next));await manager.save(customer);return manager.save(CustomerAccountMovement,{businessId:input.businessId,customerId:input.customerId,userId:input.userId,tipo:input.type,saldoAnterior:this.money(previous),cargo:this.money(charge),abono:this.money(payment),saldoNuevo:customer.saldoActual,referencia:input.reference,observaciones:input.observations});}
  async createPayment(customerId:number,dto:CreateCustomerPaymentDto,userId:number,businessId:number){return this.ds.transaction(async manager=>{const customer=await this.customer(customerId,businessId,manager,true);if(Number(customer.saldoActual)<=0)throw new BadRequestException({message:'El cliente no tiene saldo pendiente',errorCode:'NO_OUTSTANDING_BALANCE'});if(dto.monto>Number(customer.saldoActual)+0.0001)throw new BadRequestException({message:'El abono excede el saldo pendiente',errorCode:'PAYMENT_EXCEEDS_BALANCE'});const payment=await manager.save(CustomerPayment,{businessId,customerId,userId,monto:this.money(dto.monto),metodo:dto.metodo});await this.addMovement({customerId,businessId,userId,type:CustomerAccountMovementType.ABONO,payment:dto.monto,reference:`ABONO-${payment.id}`,observations:dto.observaciones},manager);await this.audit.log({userId,businessId,modulo:'CUENTAS_POR_COBRAR',accion:'ABONO_REGISTRADO',entidad:'abonos_cliente',entidadId:String(payment.id),descripcion:`Abono de ${payment.monto} registrado`},manager);return payment;});}
  async cancelPayment(paymentId:number,dto:CancelCustomerPaymentDto,userId:number,businessId:number){return this.ds.transaction(async manager=>{const payment=await manager.findOne(CustomerPayment,{where:{id:paymentId,businessId},lock:{mode:'pessimistic_write'}});if(!payment)throw new NotFoundException({message:'Abono no encontrado',errorCode:'PAYMENT_NOT_FOUND'});if(payment.cancelado)throw new BadRequestException({message:'El abono ya fue cancelado',errorCode:'PAYMENT_ALREADY_CANCELLED'});await this.customer(payment.customerId,businessId,manager,true);payment.cancelado=true;payment.motivoCancelacion=dto.motivo;payment.fechaCancelacion=new Date();await manager.save(payment);await this.addMovement({customerId:payment.customerId,businessId,userId,type:CustomerAccountMovementType.CANCELACION_ABONO,charge:Number(payment.monto),reference:`ABONO-${payment.id}`,observations:dto.motivo},manager);await this.audit.log({userId,businessId,modulo:'CUENTAS_POR_COBRAR',accion:'ABONO_CANCELADO',entidad:'abonos_cliente',entidadId:String(payment.id),descripcion:`Abono ${payment.id} cancelado`},manager);return payment;});}
  async statement(customerId:number,q:PaginationDto,businessId:number){const customer=await this.customer(customerId,businessId);const where={businessId,customerId};const [movements,total,totals]=await Promise.all([this.movements.find({where,skip:(q.page-1)*q.limit,take:q.limit,order:{createdAt:'DESC'}}),this.movements.count({where}),this.movements.createQueryBuilder('m').select('COALESCE(SUM(m.cargo),0)','cargos').addSelect('COALESCE(SUM(m.abono),0)','abonos').where('m.negocio_id=:businessId AND m.cliente_id=:customerId',{businessId,customerId}).getRawOne()]);return{saldoActual:customer.saldoActual,totalCargos:totals.cargos,totalAbonos:totals.abonos,movimientos:movements.map(m=>({fecha:m.createdAt,tipo:m.tipo,referencia:m.referencia,cargo:m.cargo,abono:m.abono,saldo:m.saldoNuevo,observaciones:m.observaciones})),meta:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
  async receivables(q:PaginationDto,businessId:number){const qb=this.customers.createQueryBuilder('c').where('c.negocio_id=:businessId AND c.saldo_actual>0',{businessId}).orderBy('c.saldo_actual','DESC').skip((q.page-1)*q.limit).take(q.limit);const [customers,aggregate]=await Promise.all([qb.getMany(),this.customers.createQueryBuilder('c').select('COALESCE(SUM(c.saldo_actual),0)','total').where('c.negocio_id=:businessId AND c.saldo_actual>0',{businessId}).getRawOne()]);const pendingTotal=await this.customers.createQueryBuilder('c').where('c.negocio_id=:businessId AND c.saldo_actual>0',{businessId}).getCount();return{totalPendiente:aggregate.total,clientesConSaldo:pendingTotal,mayoresDeudores:customers.map(c=>({clienteId:c.id,nombre:c.nombre,saldo:c.saldoActual})),meta:{page:q.page,limit:q.limit,total:pendingTotal,totalPages:Math.ceil(pendingTotal/q.limit)}};}
}
