export enum InventoryMovementType { ENTRADA='ENTRADA', VENTA='VENTA', AJUSTE_POSITIVO='AJUSTE_POSITIVO', AJUSTE_NEGATIVO='AJUSTE_NEGATIVO', DEVOLUCION='DEVOLUCION', REGALO='REGALO', CANCELACION_VENTA='CANCELACION_VENTA' }
export enum SaleStatus { COMPLETADA='COMPLETADA', CANCELADA='CANCELADA' }
export enum PromotionType { COMPRA_N_LLEVA_M='COMPRA_N_LLEVA_M', DESCUENTO_PORCENTAJE='DESCUENTO_PORCENTAJE', DESCUENTO_MONTO='DESCUENTO_MONTO', LEALTAD='LEALTAD' }
export enum RewardStatus { DISPONIBLE='DISPONIBLE', CANJEADA='CANJEADA', EXPIRADA='EXPIRADA', CANCELADA='CANCELADA' }
export enum BusinessStatus { ACTIVO='ACTIVO', SUSPENDIDO='SUSPENDIDO', DESACTIVADO='DESACTIVADO' }
export enum BusinessMembershipStatus { ACTIVA='ACTIVA', INACTIVA='INACTIVA' }
